// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameproto/student_config.proto

/*
Package gameproto is a generated protocol buffer package.

It is generated from these files:
	gameproto/student_config.proto

It has these top-level messages:
	StudentConfig
	Student
	TeacherItemDefine
	StudentItemDefine
*/
package gameproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Defined in table: StudentConfig
type StudentConfig struct {
	TeacherItem []*TeacherItemDefine `protobuf:"bytes,1,rep,name=TeacherItem" json:"TeacherItem,omitempty"`
	StudentItem []*StudentItemDefine `protobuf:"bytes,2,rep,name=StudentItem" json:"StudentItem,omitempty"`
}

func (m *StudentConfig) Reset()                    { *m = StudentConfig{} }
func (m *StudentConfig) String() string            { return proto.CompactTextString(m) }
func (*StudentConfig) ProtoMessage()               {}
func (*StudentConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StudentConfig) GetTeacherItem() []*TeacherItemDefine {
	if m != nil {
		return m.TeacherItem
	}
	return nil
}

func (m *StudentConfig) GetStudentItem() []*StudentItemDefine {
	if m != nil {
		return m.StudentItem
	}
	return nil
}

// Defined in table: StudentItem
type Student struct {
	// 姓名
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	// 年龄
	Age int32 `protobuf:"varint,2,opt,name=Age" json:"Age,omitempty"`
}

func (m *Student) Reset()                    { *m = Student{} }
func (m *Student) String() string            { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()               {}
func (*Student) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

// Defined in table: TeacherItem
type TeacherItemDefine struct {
	ID          int32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	TeacherName string `protobuf:"bytes,2,opt,name=TeacherName" json:"TeacherName,omitempty"`
}

func (m *TeacherItemDefine) Reset()                    { *m = TeacherItemDefine{} }
func (m *TeacherItemDefine) String() string            { return proto.CompactTextString(m) }
func (*TeacherItemDefine) ProtoMessage()               {}
func (*TeacherItemDefine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TeacherItemDefine) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TeacherItemDefine) GetTeacherName() string {
	if m != nil {
		return m.TeacherName
	}
	return ""
}

// Defined in table: StudentItem
type StudentItemDefine struct {
	ID      int32      `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Info    *Student   `protobuf:"bytes,2,opt,name=Info" json:"Info,omitempty"`
	Friends []*Student `protobuf:"bytes,3,rep,name=Friends" json:"Friends,omitempty"`
	Day     int32      `protobuf:"varint,4,opt,name=Day" json:"Day,omitempty"`
}

func (m *StudentItemDefine) Reset()                    { *m = StudentItemDefine{} }
func (m *StudentItemDefine) String() string            { return proto.CompactTextString(m) }
func (*StudentItemDefine) ProtoMessage()               {}
func (*StudentItemDefine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StudentItemDefine) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *StudentItemDefine) GetInfo() *Student {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *StudentItemDefine) GetFriends() []*Student {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *StudentItemDefine) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func init() {
	proto.RegisterType((*StudentConfig)(nil), "gameproto.StudentConfig")
	proto.RegisterType((*Student)(nil), "gameproto.Student")
	proto.RegisterType((*TeacherItemDefine)(nil), "gameproto.TeacherItemDefine")
	proto.RegisterType((*StudentItemDefine)(nil), "gameproto.StudentItemDefine")
}

func init() { proto.RegisterFile("gameproto/student_config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x4d, 0x6a, 0xe9, 0x04, 0xc5, 0xce, 0x69, 0x0f, 0x22, 0x21, 0x07, 0xc9, 0x41,
	0x52, 0xa8, 0x77, 0x41, 0x5c, 0x85, 0x5c, 0x3c, 0xac, 0xde, 0x65, 0x6d, 0x27, 0x31, 0x87, 0x6c,
	0x24, 0x8d, 0x87, 0xfe, 0x06, 0x0f, 0xfe, 0x65, 0xc9, 0xb4, 0x0d, 0x0b, 0xeb, 0x6d, 0x76, 0xde,
	0xfb, 0x1e, 0xf3, 0x16, 0xae, 0x6b, 0xdb, 0xd2, 0x57, 0xdf, 0x0d, 0xdd, 0x6a, 0x37, 0x7c, 0x6f,
	0xc9, 0x0d, 0xef, 0x9b, 0xce, 0x55, 0x4d, 0x5d, 0xf0, 0x12, 0x17, 0x93, 0x9e, 0xfd, 0x0a, 0x38,
	0x7f, 0x3d, 0x78, 0x1e, 0xd9, 0x82, 0xf7, 0x90, 0xbc, 0x91, 0xdd, 0x7c, 0x52, 0x5f, 0x0e, 0xd4,
	0x2a, 0x91, 0x46, 0x79, 0xb2, 0xbe, 0x2a, 0x26, 0xa4, 0xf0, 0x54, 0x4d, 0x55, 0xe3, 0xc8, 0xf8,
	0xc0, 0xc8, 0x1f, 0x03, 0x99, 0x97, 0x01, 0xef, 0xa9, 0x27, 0xde, 0x5b, 0x65, 0x2b, 0x98, 0x1f,
	0x9f, 0x88, 0x10, 0xbf, 0xd8, 0x96, 0x94, 0x48, 0x45, 0xbe, 0x30, 0x3c, 0xe3, 0x25, 0x44, 0x0f,
	0x35, 0x29, 0x99, 0x8a, 0x7c, 0x66, 0xc6, 0x31, 0x7b, 0x82, 0x65, 0x70, 0x12, 0x5e, 0x80, 0x2c,
	0x35, 0x83, 0x33, 0x23, 0x4b, 0x8d, 0xe9, 0xd4, 0x8a, 0x13, 0x25, 0x27, 0xfa, 0xab, 0xec, 0x47,
	0xc0, 0x32, 0x38, 0x2d, 0xc8, 0xb9, 0x81, 0xb8, 0x74, 0x55, 0xc7, 0x01, 0xc9, 0x1a, 0xc3, 0x5a,
	0x86, 0x75, 0xbc, 0x85, 0xf9, 0x73, 0xdf, 0x90, 0xdb, 0xee, 0x54, 0xc4, 0x3f, 0xf0, 0x9f, 0xf5,
	0x64, 0x19, 0x4b, 0x69, 0xbb, 0x57, 0xf1, 0xa1, 0x94, 0xb6, 0xfb, 0x8f, 0x33, 0x76, 0xde, 0xfd,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xa2, 0x47, 0xd9, 0xcb, 0x01, 0x00, 0x00,
}
