// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account    string
	Email      string
	EmailSend  string
	EmailTimer string
	User       string
}{
	Account:    "account",
	Email:      "email",
	EmailSend:  "email_send",
	EmailTimer: "email_timer",
	User:       "user",
}
