// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEmails(t *testing.T) {
	t.Parallel()

	query := Emails()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEmailsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEmailsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Emails().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEmailsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EmailSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEmailsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EmailExists(tx, o.EmailID)
	if err != nil {
		t.Errorf("Unable to check if Email exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EmailExists to return true, but got false.")
	}
}

func testEmailsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	emailFound, err := FindEmail(tx, o.EmailID)
	if err != nil {
		t.Error(err)
	}

	if emailFound == nil {
		t.Error("want a record, got nil")
	}
}

func testEmailsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Emails().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testEmailsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Emails().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEmailsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	emailOne := &Email{}
	emailTwo := &Email{}
	if err = randomize.Struct(seed, emailOne, emailDBTypes, false, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}
	if err = randomize.Struct(seed, emailTwo, emailDBTypes, false, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = emailOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = emailTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Emails().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEmailsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	emailOne := &Email{}
	emailTwo := &Email{}
	if err = randomize.Struct(seed, emailOne, emailDBTypes, false, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}
	if err = randomize.Struct(seed, emailTwo, emailDBTypes, false, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = emailOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = emailTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testEmailsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEmailsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(emailColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEmailsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testEmailsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EmailSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testEmailsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Emails().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	emailDBTypes = map[string]string{`Attaches`: `text`, `Content`: `text`, `CreateTime`: `int`, `EmailID`: `bigint`, `EmailType`: `tinyint`, `EndTime`: `int`, `StartTime`: `int`, `Title`: `varchar`, `UpdatedAt`: `timestamp`}
	_            = bytes.MinRead
)

func testEmailsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(emailPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(emailColumns) == len(emailPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, emailDBTypes, true, emailPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEmailsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(emailColumns) == len(emailPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Email{}
	if err = randomize.Struct(seed, o, emailDBTypes, true, emailColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, emailDBTypes, true, emailPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(emailColumns, emailPrimaryKeyColumns) {
		fields = emailColumns
	} else {
		fields = strmangle.SetComplement(
			emailColumns,
			emailPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EmailSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEmailsUpsert(t *testing.T) {
	t.Parallel()

	if len(emailColumns) == len(emailPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLEmailUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Email{}
	if err = randomize.Struct(seed, &o, emailDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Email: %s", err)
	}

	count, err := Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, emailDBTypes, false, emailPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Email struct: %s", err)
	}

	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Email: %s", err)
	}

	count, err = Emails().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
