// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.msg

package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the msg package it is being compiled against.
// A compilation error at this line likely means your copy of the
// msg package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the msg package

type PhoneType int32

const (
	PhoneType_HOME PhoneType = 0
	PhoneType_WORK PhoneType = 1
)

var PhoneType_name = map[int32]string{
	0: "HOME",
	1: "WORK",
}
var PhoneType_value = map[string]int32{
	"HOME": 0,
	"WORK": 1,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}
func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_test_54b6d761c402c179, []int{0}
}

type Person struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PhoneType            PhoneType `protobuf:"varint,3,opt,name=phoneType,enum=test.PhoneType" json:"phoneType,omitempty"`
	Age                  string    `protobuf:"bytes,4,opt,name=age" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_54b6d761c402c179, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetPhoneType() PhoneType {
	if m != nil {
		return m.PhoneType
	}
	return PhoneType_HOME
}

func (m *Person) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

type Contact struct {
	Person               []*Person `protobuf:"bytes,1,rep,name=person" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_54b6d761c402c179, []int{1}
}
func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (dst *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(dst, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "test.Person")
	proto.RegisterType((*Contact)(nil), "test.Contact")
	proto.RegisterEnum("test.PhoneType", PhoneType_name, PhoneType_value)
}

func init() { proto.RegisterFile("test.msg", fileDescriptor_test_54b6d761c402c179) }

var fileDescriptor_test_54b6d761c402c179 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x72, 0xb9, 0xd8, 0x02, 0x52,
	0x8b, 0x8a, 0xf3, 0xf3, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58,
	0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x5d, 0x2e, 0xce, 0x82, 0x8c, 0xfc, 0xbc, 0xd4, 0x90, 0xca,
	0x82, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x7e, 0x3d, 0xb0, 0x99, 0x01, 0x30, 0xe1,
	0x20, 0x84, 0x0a, 0x21, 0x01, 0x2e, 0xe6, 0xc4, 0xf4, 0x54, 0x09, 0x16, 0xb0, 0x09, 0x20, 0xa6,
	0x92, 0x3e, 0x17, 0xbb, 0x73, 0x7e, 0x5e, 0x49, 0x62, 0x72, 0x89, 0x90, 0x0a, 0x17, 0x5b, 0x01,
	0xd8, 0x66, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x1e, 0xa8, 0x41, 0x60, 0xb1, 0x20, 0xa8,
	0x9c, 0x96, 0x3c, 0x17, 0x27, 0xdc, 0x68, 0x21, 0x0e, 0x2e, 0x16, 0x0f, 0x7f, 0x5f, 0x57, 0x01,
	0x06, 0x10, 0x2b, 0xdc, 0x3f, 0xc8, 0x5b, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x1b, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb3, 0x72, 0x5a, 0x72, 0xdb, 0x00, 0x00, 0x00,
}
