# Generated by github.com/davyxu/tabtoy
# Version: 2.9.1
# Modify by nuyan
TeacherItem: [
	{ID: 1001, TeacherName: "Mr Xu10" },
	{ID: 1002, TeacherName: "Mr Bao" }
]

StudentItem: [
	{ID: 1003, Info: { Name: "xu", Age: 30 }, Friends:[ { Name: "jia", Age: 30 }, { Name: "long2", Age: 20 } ], Day: 30 },
	{ID: 1002, Info: { Name: "宝宝", Age: 1 }, Day: 21 }
]

