// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hello struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_53bc9ed515ffd02a, []int{0}
}
func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (dst *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(dst, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type World struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *World) Reset()         { *m = World{} }
func (m *World) String() string { return proto.CompactTextString(m) }
func (*World) ProtoMessage()    {}
func (*World) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_53bc9ed515ffd02a, []int{1}
}
func (m *World) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_World.Unmarshal(m, b)
}
func (m *World) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_World.Marshal(b, m, deterministic)
}
func (dst *World) XXX_Merge(src proto.Message) {
	xxx_messageInfo_World.Merge(dst, src)
}
func (m *World) XXX_Size() int {
	return xxx_messageInfo_World.Size(m)
}
func (m *World) XXX_DiscardUnknown() {
	xxx_messageInfo_World.DiscardUnknown(m)
}

var xxx_messageInfo_World proto.InternalMessageInfo

func (m *World) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *World) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *World) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*Hello)(nil), "hello.hello")
	proto.RegisterType((*World)(nil), "hello.world")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_hello_53bc9ed515ffd02a) }

var fileDescriptor_hello_53bc9ed515ffd02a = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xb4, 0xb9, 0x20, 0x0c,
	0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14,
	0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30,
	0x5b, 0xc9, 0x96, 0x8b, 0xb5, 0x3c, 0xbf, 0x28, 0x27, 0x85, 0x18, 0xc5, 0x42, 0x02, 0x5c, 0xcc,
	0x89, 0xe9, 0xa9, 0x12, 0xcc, 0x60, 0x45, 0x20, 0x66, 0x12, 0x1b, 0xd8, 0x66, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x15, 0x53, 0xdb, 0x11, 0x88, 0x00, 0x00, 0x00,
}
